//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bankrupt.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GameResultResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResultResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bankrupt.Application.Resources.GameResultResource", typeof(GameResultResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cautious.
        /// </summary>
        public static string PlayerTypeCautious {
            get {
                return ResourceManager.GetString("PlayerTypeCautious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demanding.
        /// </summary>
        public static string PlayerTypeDemanding {
            get {
                return ResourceManager.GetString("PlayerTypeDemanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impulsive.
        /// </summary>
        public static string PlayerTypeImpulsive {
            get {
                return ResourceManager.GetString("PlayerTypeImpulsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        public static string PlayerTypeRandom {
            get {
                return ResourceManager.GetString("PlayerTypeRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string PlayerTypeUndefined {
            get {
                return ResourceManager.GetString("PlayerTypeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Time Out?.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner Type.
        /// </summary>
        public static string WinnerType {
            get {
                return ResourceManager.GetString("WinnerType", resourceCulture);
            }
        }
    }
}
